os: linux
dist: trusty
language: python
services: docker

env:
  global:
    - BASE=ams595/desktop:latest
    - VERSION=debug

before_script:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - docker pull $BASE

script:
  # Build only if the commit range of a push contains Dockerfile or .travis.yml
  - '[[ "$TRAVIS_EVENT_TYPE" == "push" && -n "$TRAVIS_COMMIT_RANGE" &&
        -n $(git log --since $(docker inspect $BASE | grep Created | perl -e "s/.+\"([\d-:T]+).+$/\$1/g" -p)) &&
        -z "$(git diff --name-only $TRAVIS_COMMIT_RANGE |
            grep -e Dockerfile -e .travis.yml -e image -e WELCOME)" ]] ||
    (docker build --tag ams595/desktop:debug --tag ams595/desktop:valgrind . &&
     docker rmi ams595/desktop:latest &&
     docker push ams595/desktop &&
     touch success)'
  # Test startup scripts
  - './ams595_desktop.py -d -n -t $VERSION && docker stop $(docker ps -q) &&
     ./ams595_jupyter.py -d -n -t $VERSION && docker stop $(docker ps -q)'
  - docker images
